package io.factry.historian.gateway;

import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.DefaultValue;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Description;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.FormCategory;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.FormField;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Label;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Required;
import com.inductiveautomation.ignition.gateway.web.nav.FormFieldType;

public record FactryHistorianConfig(
        @FormCategory("Connection")
        @Label("Token*")
        @FormField(FormFieldType.TEXTAREA)
        @DefaultValue("")
        @Required
        @Description("Collector token generated by Factry Historian. Connection settings (host, port, collector ID) are extracted automatically.")
        String token,

        @FormCategory("Connection")
        @Label("Use TLS")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("true")
        @Description("Use TLS for gRPC connection. Disable for plaintext connections (e.g. local test servers).")
        boolean useTls,

        @FormCategory("Connection")
        @Label("Skip TLS Verification")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Disable TLS certificate verification. Use only for testing with self-signed certificates.")
        boolean skipTlsVerification,

        @FormCategory("Advanced")
        @Label("Batch Size")
        @FormField(FormFieldType.NUMBER)
        @DefaultValue("100")
        @Description("Data points are buffered and written in batches. A write is triggered when this many points have accumulated, or when the batch interval expires — whichever comes first.")
        int batchSize,

        @FormCategory("Advanced")
        @Label("Batch Interval (ms)")
        @FormField(FormFieldType.NUMBER)
        @DefaultValue("5000")
        @Description("Maximum time in milliseconds to wait before writing buffered data points. A write is triggered when this interval expires, or when the batch size is reached — whichever comes first.")
        int batchIntervalMs,

        @FormCategory("Advanced")
        @Label("Debug Logging")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Enable detailed debug logging")
        boolean debugLogging,

        @FormCategory("Advanced")
        @Label("Store and Forward Engine")
        @FormField(FormFieldType.TEXT)
        @DefaultValue("")
        @Description("Name of the S&F engine for buffering. Leave empty to disable S&F.")
        String storeAndForwardEngine
) {
    public FactryHistorianSettings toSettings() {
        FactryHistorianSettings settings = new FactryHistorianSettings();
        settings.setToken(token);
        settings.setUseTls(useTls);
        settings.setSkipTlsVerification(skipTlsVerification);
        settings.setBatchSize(batchSize);
        settings.setBatchIntervalMs(batchIntervalMs);
        settings.setDebugLogging(debugLogging);
        settings.setStoreAndForwardEngine(storeAndForwardEngine);
        return settings;
    }

    public static FactryHistorianConfig fromSettings(FactryHistorianSettings settings) {
        return new FactryHistorianConfig(
                settings.getToken(),
                settings.isUseTls(),
                settings.isSkipTlsVerification(),
                settings.getBatchSize(),
                settings.getBatchIntervalMs(),
                settings.isDebugLogging(),
                settings.getStoreAndForwardEngine()
        );
    }
}
