package io.factry.historian.gateway;

import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.DefaultValue;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Description;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.FormCategory;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.FormField;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Label;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.NonSecret;
import com.inductiveautomation.ignition.gateway.dataroutes.openapi.annotations.Required;
import com.inductiveautomation.ignition.gateway.web.nav.FormFieldType;

public record FactryHistorianConfig(
        @FormCategory("Connection")
        @Label("Token*")
        @FormField(FormFieldType.TEXTAREA)
        @DefaultValue("")
        @Required
        @NonSecret
        @Description("Collector token generated by Factry Historian. Connection settings (host, port, collector ID) are extracted automatically.")
        String token,

        @FormCategory("Connection")
        @Label("Use TLS")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("true")
        @Description("Use TLS for gRPC connection. Disable for plaintext connections (e.g. local test servers).")
        boolean useTls,

        @FormCategory("Connection")
        @Label("Skip TLS Verification")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Disable TLS certificate verification. Use only for testing with self-signed certificates.")
        boolean skipTlsVerification,

        @FormCategory("Advanced")
        @Label("Batch Size")
        @FormField(FormFieldType.NUMBER)
        @DefaultValue("10")
        @Description("Data points are buffered and written in batches. A write is triggered when this many points have accumulated, or when the batch interval expires — whichever comes first. (default: 10)")
        int batchSize,

        @FormCategory("Advanced")
        @Label("Batch Interval (ms)")
        @FormField(FormFieldType.NUMBER)
        @DefaultValue("5000")
        @Description("Maximum time in milliseconds to wait before writing buffered data points. A write is triggered when this interval expires, or when the batch size is reached — whichever comes first. (default: 5000)")
        int batchIntervalMs,

        @FormCategory("Advanced")
        @Label("Debug Logging")
        @FormField(FormFieldType.CHECKBOX)
        @DefaultValue("false")
        @Description("Enable detailed debug logging.")
        boolean debugLogging,

        @FormCategory("Advanced")
        @Label("Tag Path Delimiter")
        @FormField(FormFieldType.TEXT)
        @DefaultValue("")
        @Description("Character Ignition uses to parse a tag path into a tree view in the Power Chart and tag browser. "
                + "Leave empty (default) to show tags as a flat list (any '/' in the path is preserved with a special character so it is not split). "
                + "Set '/' to split the path into a hierarchical tree. "
                + "Set another character (e.g. '.') to build the tree by splitting on that character instead.")
        String delimiter
) {
    public FactryHistorianSettings toSettings() {
        FactryHistorianSettings settings = new FactryHistorianSettings();
        settings.setToken(token);
        settings.setUseTls(useTls);
        settings.setSkipTlsVerification(skipTlsVerification);
        settings.setBatchSize(batchSize);
        settings.setBatchIntervalMs(batchIntervalMs);
        settings.setDebugLogging(debugLogging);
        settings.setDelimiter(delimiter);
        return settings;
    }

    public static FactryHistorianConfig fromSettings(FactryHistorianSettings settings) {
        return new FactryHistorianConfig(
                settings.getToken(),
                settings.isUseTls(),
                settings.isSkipTlsVerification(),
                settings.getBatchSize(),
                settings.getBatchIntervalMs(),
                settings.isDebugLogging(),
                settings.getDelimiter()
        );
    }
}
