/*
 * This project was generated by the Ignition Module Generator.  It is intended to provide initial project structure
 * and minimize boilerplate.  This initial project is a starting point for your own module projects using the Gradle
 * build system.  It is not intended to be a replacement for learning and understanding Gradle.
 *
 * Generator: https://github.com/inductiveautomation/ignition-module-tools/tree/master/generator/generator-core
 * Gradle Docs: https://docs.gradle.org/current/userguide/userguide.html
 */

import java.util.Date
import java.text.SimpleDateFormat

plugins {
    id("io.ia.sdk.modl") version("0.4.1")
}

val sdk_version by extra("8.3.3")

val buildNumberFile = file("build-number.txt")
val buildNumber = if (buildNumberFile.exists()) buildNumberFile.readText().trim().toInt() else 0

val timestamp = SimpleDateFormat("yyyyMMddHH").format(Date())

allprojects {
    version = "0.3.${buildNumber}"
}

ignitionModule {
    /*
     * Human readable name of the module, as will be displayed on the gateway status page
     */
    name.set("Factry Historian")

    /*
     * Name of the '.modl' file to be created, without file extension.
     */
    fileName.set("Factry-Historian")
    /*
     * Unique identifier for the module.  Reverse domain convention is recommended (e.g.: com.mycompany.charting-module)
     */
    id.set("io.factry.historian.FactryHistorian")

    /*
     * Version of the module.  Here being set to the same version that gradle uses, up above in this file.
     */
    moduleVersion.set("${project.version}.${timestamp}")

    moduleDescription.set("Custom historian module that stores tag history data in external Factry Historian system.")

    /*
     * Minimum version of Ignition required for the module to function correctly.  This typically won't change over
     * the course of a major Ignition (7.9, 8.0, etc) version, except for when the Ignition Platform adds/changes APIs
     * used by the module.
     */
    // Note: SDK version (8.1.20) is for compilation, but we target Ignition 8.3+ runtime
    requiredIgnitionVersion.set("8.3.0")
    /*
     *  This is a map of String: String, where the 'key' represents the fully qualified path to the project
     *  (using gradle path syntax), and the value is the shorthand Scope string.
     *  Example entry: listOf( ":gateway" to "G", ":common" to "GC", ":vision-client" to "C" )
     */
    projectScopes.putAll(mapOf(
        ":client" to "CD",
        ":common" to "GCD",
        ":designer" to "D",
        ":gateway" to "G"
    ))

    /*
     * Add your module dependencies here, following the examples, with scope being one or more of G, C or D,
     * for (G)ateway, (D)esigner, Vision (C)lient.
     * Example:
     * moduleDependencies = mapOf(
     *    "CD" to "com.inductiveautomation.vision",
     *    "G" to "com.inductiveautomation.opcua"
     *  )
     */
    moduleDependencies.set(mapOf<String, String>())

    /*
     * Add required module dependencies here, following the examples, with scope being one or more of G, C or D,
     * for (G)ateway, (D)esigner, Vision (C)lient.
     *
     * Example:
     *   moduleDependencySpecs {
     *      register("com.inductiveautomation.vision") {
     *          scope = "GCD"
     *          required = true
     *      }
     *      // register("com.another.mod") { ...
     *   }
     *
     * If any of module's required module dependencies are not present, the
     * gateway will fault on loading the module.
     *
     * NOTE: For modules targeting Ignition 8.3 and later. Use `moduleDependencies` for 8.1 and earlier.
     * This property will only add the "required" flag if {requiredIgnitionVersion} is at least 8.3
     *
     */
    moduleDependencySpecs {
        // Historian Core module is required for our AbstractHistorian implementation
        // Historian related packages are in a separate artifact,
        // because the historian is now a dedicated module
        register("com.inductiveautomation.historian") {
            scope = "G"  // Gateway scope only
            required = true  // Module won't load without this dependency
        }
    }

    /*
     * Map of fully qualified hook class to the shorthand scope.  Only one scope may apply to a class, and each scope
     * must have no more than single class registered.  You may omit scope registrations if they do not apply.
     *
     * Example entry: "com.myorganization.vectorizer.VectorizerDesignerHook" to "D"
     */
    hooks.putAll(mapOf(
        "io.factry.historian.gateway.FactryHistorianGatewayHook" to "G",
        "io.factry.historian.client.FactryHistorianClientHook" to "C",
        "io.factry.historian.designer.FactryHistorianDesignerHook" to "D"
    ))

    /*
     * Optional 'documentation' settings.  Supply the files that would be desired to end up in the 'doc' dir of the
     * assembled module, and specify the path to the index.html file inside that folder. In this commented-out
     * example, the html files being collected are located in the module root project in `src/docs/`
     */
    // the files to collect into the documentation dir, with example implementation
    // documentationFiles.from(project.file("src/docs/"))

    /* The path from the root documentation dir to the index file, or filename if in the root doc dir. */
    // documentationIndex.set("index.html")

    /*
     * Optional unsigned modl settings. If true, modl signing will be skipped. This is not for production and should
     * be used merely for development testing
     */
    skipModlSigning.set(project.findProperty("skipSigning")?.toString()?.toBoolean() ?: false)
}

tasks.named("build") {
    doLast {
        buildNumberFile.writeText("${buildNumber + 1}")
    }
}

// Deploy tasks — copy module to Ignition and restart the container
val ignitionModlDir = file("ignition/data/modules")

tasks.register<Copy>("copy") {
    group = "deploy"
    description = "Copy the built module to the Ignition modules directory"
    dependsOn("build")
    from(layout.buildDirectory.file("Factry-Historian.modl"))
    into(ignitionModlDir)
    rename { "Factry-Historian.modl" }
}

tasks.register<Exec>("restart") {
    group = "deploy"
    description = "Restart the Ignition Docker container"
    dependsOn("copy")
    commandLine("docker", "compose", "restart", "ignition")
}
