// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: factry/historian/v1/historian.proto

package historianpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistorianCollector_Store_FullMethodName = "/factry.historian.v1.HistorianCollector/Store"
)

// HistorianCollectorClient is the client API for HistorianCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistorianCollectorClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
}

type historianCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewHistorianCollectorClient(cc grpc.ClientConnInterface) HistorianCollectorClient {
	return &historianCollectorClient{cc}
}

func (c *historianCollectorClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, HistorianCollector_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistorianCollectorServer is the server API for HistorianCollector service.
// All implementations must embed UnimplementedHistorianCollectorServer
// for forward compatibility.
type HistorianCollectorServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	mustEmbedUnimplementedHistorianCollectorServer()
}

// UnimplementedHistorianCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistorianCollectorServer struct{}

func (UnimplementedHistorianCollectorServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedHistorianCollectorServer) mustEmbedUnimplementedHistorianCollectorServer() {}
func (UnimplementedHistorianCollectorServer) testEmbeddedByValue()                            {}

// UnsafeHistorianCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistorianCollectorServer will
// result in compilation errors.
type UnsafeHistorianCollectorServer interface {
	mustEmbedUnimplementedHistorianCollectorServer()
}

func RegisterHistorianCollectorServer(s grpc.ServiceRegistrar, srv HistorianCollectorServer) {
	// If the following call panics, it indicates UnimplementedHistorianCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistorianCollector_ServiceDesc, srv)
}

func _HistorianCollector_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorianCollectorServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorianCollector_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorianCollectorServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistorianCollector_ServiceDesc is the grpc.ServiceDesc for HistorianCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistorianCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "factry.historian.v1.HistorianCollector",
	HandlerType: (*HistorianCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _HistorianCollector_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "factry/historian/v1/historian.proto",
}
