// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: factry/historian/v1/historian.proto

package historianpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagPath       string                 `protobuf:"bytes,1,opt,name=tag_path,json=tagPath,proto3" json:"tag_path,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ValueInt      int32                  `protobuf:"varint,3,opt,name=value_int,json=valueInt,proto3" json:"value_int,omitempty"`
	ValueDouble   float64                `protobuf:"fixed64,4,opt,name=value_double,json=valueDouble,proto3" json:"value_double,omitempty"`
	Quality       int32                  `protobuf:"varint,5,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagSample) Reset() {
	*x = TagSample{}
	mi := &file_factry_historian_v1_historian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSample) ProtoMessage() {}

func (x *TagSample) ProtoReflect() protoreflect.Message {
	mi := &file_factry_historian_v1_historian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSample.ProtoReflect.Descriptor instead.
func (*TagSample) Descriptor() ([]byte, []int) {
	return file_factry_historian_v1_historian_proto_rawDescGZIP(), []int{0}
}

func (x *TagSample) GetTagPath() string {
	if x != nil {
		return x.TagPath
	}
	return ""
}

func (x *TagSample) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TagSample) GetValueInt() int32 {
	if x != nil {
		return x.ValueInt
	}
	return 0
}

func (x *TagSample) GetValueDouble() float64 {
	if x != nil {
		return x.ValueDouble
	}
	return 0
}

func (x *TagSample) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*TagSample           `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_factry_historian_v1_historian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factry_historian_v1_historian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_factry_historian_v1_historian_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetSamples() []*TagSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_factry_historian_v1_historian_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_factry_historian_v1_historian_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_factry_historian_v1_historian_proto_rawDescGZIP(), []int{2}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StoreResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_factry_historian_v1_historian_proto protoreflect.FileDescriptor

const file_factry_historian_v1_historian_proto_rawDesc = "" +
	"\n" +
	"#factry/historian/v1/historian.proto\x12\x13factry.historian.v1\"\xa3\x01\n" +
	"\tTagSample\x12\x19\n" +
	"\btag_path\x18\x01 \x01(\tR\atagPath\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1b\n" +
	"\tvalue_int\x18\x03 \x01(\x05R\bvalueInt\x12!\n" +
	"\fvalue_double\x18\x04 \x01(\x01R\vvalueDouble\x12\x18\n" +
	"\aquality\x18\x05 \x01(\x05R\aquality\"H\n" +
	"\fStoreRequest\x128\n" +
	"\asamples\x18\x01 \x03(\v2\x1e.factry.historian.v1.TagSampleR\asamples\"Y\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count2d\n" +
	"\x12HistorianCollector\x12N\n" +
	"\x05Store\x12!.factry.historian.v1.StoreRequest\x1a\".factry.historian.v1.StoreResponseBW\n" +
	"\x19io.factry.historian.protoB\x0eHistorianProtoP\x01Z(factry-historian-proxy/proto/historianpbb\x06proto3"

var (
	file_factry_historian_v1_historian_proto_rawDescOnce sync.Once
	file_factry_historian_v1_historian_proto_rawDescData []byte
)

func file_factry_historian_v1_historian_proto_rawDescGZIP() []byte {
	file_factry_historian_v1_historian_proto_rawDescOnce.Do(func() {
		file_factry_historian_v1_historian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_factry_historian_v1_historian_proto_rawDesc), len(file_factry_historian_v1_historian_proto_rawDesc)))
	})
	return file_factry_historian_v1_historian_proto_rawDescData
}

var file_factry_historian_v1_historian_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_factry_historian_v1_historian_proto_goTypes = []any{
	(*TagSample)(nil),     // 0: factry.historian.v1.TagSample
	(*StoreRequest)(nil),  // 1: factry.historian.v1.StoreRequest
	(*StoreResponse)(nil), // 2: factry.historian.v1.StoreResponse
}
var file_factry_historian_v1_historian_proto_depIdxs = []int32{
	0, // 0: factry.historian.v1.StoreRequest.samples:type_name -> factry.historian.v1.TagSample
	1, // 1: factry.historian.v1.HistorianCollector.Store:input_type -> factry.historian.v1.StoreRequest
	2, // 2: factry.historian.v1.HistorianCollector.Store:output_type -> factry.historian.v1.StoreResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_factry_historian_v1_historian_proto_init() }
func file_factry_historian_v1_historian_proto_init() {
	if File_factry_historian_v1_historian_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_factry_historian_v1_historian_proto_rawDesc), len(file_factry_historian_v1_historian_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_factry_historian_v1_historian_proto_goTypes,
		DependencyIndexes: file_factry_historian_v1_historian_proto_depIdxs,
		MessageInfos:      file_factry_historian_v1_historian_proto_msgTypes,
	}.Build()
	File_factry_historian_v1_historian_proto = out.File
	file_factry_historian_v1_historian_proto_goTypes = nil
	file_factry_historian_v1_historian_proto_depIdxs = nil
}
